config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  resources :orders
  resources :line_items
  devise_for :users

  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get  'branding' => 'storefront#items_by_brand'

  resources :categories
  resources :products
 

end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.order(:name)
  end

  def items_by_category
  	# link to this page is: 
  	# <%= link_to categorical_path(category_id: product.category.id) %>
  	@products = Product.where(category: params[:category_id])
  	@category = Category.find(params[:category_id])
  end

  def items_by_brand
  	# link to this page is: 
  	# <%= link_to branding_path(brand: product.brand) %>
  	@products = Product.where(brand: params[:brand])
  	@brand = params[:brand]
  end
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/storefront/_productdisplay.html.erb
<div class="row">
<% @products.each do |product| %>
  <div class="col-md-4">
  <div class="well center-it">
  		<b><%= link_to product.name, product %></b><br>
  		<%= image_tag product.image.url, height: "75" %> <br>
      <%= number_to_currency product.price %> <br>
      
      
      <a href="" data-toggle="modal" data-target="#myModal_<%= product.id %>">
        <button class="btn-sm btn-info">
      	 <span class="glyphicon glyphicon-plus"></span>Quick Info
        </button>
      </a>

<br>

<%= link_to product do %>
	<button type="button" class="btn-sm btn-default"> 
		<span class="glyphicon glyphicon-eye-open"></span>
		<% end %>
	</button>
<%= link_to edit_product_path(product) do %>
	<button type="button" class="btn-sm btn-default"> 
		<span class="glyphicon glyphicon-pencil"></span>
		<% end %>
	</button>
<%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
	<button type="button" class="btn-sm btn-default"> 
		<span class="glyphicon glyphicon-trash"></span>
		<% end %>
	</button>
	
	</div>
  </div>
<!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="myModal_<%=product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= "#{product.name}" %></h4>
      </div>
      <div class="modal-body">

  			<%= image_tag product.image.url, height: "75" %> <br>
      	<%= number_to_currency product.price %> <br>
        <%= product.description %>
      	<p><b> Brand</b>: <%= link_to "#{product.brand}",  branding_path(brand: product.brand)  %></p>
      	<p><b> Category</b>: <%= link_to "#{product.category.name}", categorical_path(category_id: product.category.id) %></p>
     		<p><b>Product Rating</b>:<%= "#{product.rating }" %>/10 </p>

       

      </div>
      <div class="modal-footer">
        <p>
          <%= form_tag add_to_cart_path do %>
            <%= hidden_field_tag :product_id, product.id %>
            <%= number_field_tag :quantity, nil, placeholder: "How Many?" %>
            <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>


<% end %>
</div>







<br>

<%= link_to new_product_path  do %>
  <button type="button" class="btn btn-default">
      <span class="glyphicon glyphicon-plus"> Add New Product</span>
      <% end %>
    </button>

app/views/storefront/_purchase.html.erb
<p>
	<%= form_tag add_to_cart_path do %>
		<%= hidden_field_tag :product_id, product.id %>
		<%= number_field_tag :quantity, nil, placeholder: "How Many?" %>
		<%= submit_tag "Add to Cart", class: "btn btn-primary" %>
	<% end %>
</p>

app/views/storefront/all_items.html.erb
<h1>All Items</h1>

<%= render 'productdisplay' %>

app/views/storefront/items_by_brand.html.erb
<h1>Items By Brand</h1>
<h2><%= @brand %></h2>

<%= render 'productdisplay' %>

app/views/storefront/items_by_category.html.erb
<h1>Items By Category</h1>
<h2><%= @category.name %></h2>

<%= render 'productdisplay' %>