config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  resources :orders
  resources :line_items
  devise_for :users

  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get  'branding' => 'storefront#items_by_brand'

  resources :categories
  resources :products
 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amalizon</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "All Products", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse by Category <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
              <% end %>
            </ul>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse by Brand <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
            </ul>
          </li>          
        </ul>
         

        
        
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "View Cart", view_order_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Welcome, #{current_user.email}!", root_path %> </li>
          <li><%= link_to edit_user_registration_path do %><i class="fa fa-pencil"></i>Edit Profile
            <% end %>
          </li>
          <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out"></i>Sign Out
            <% end %>
          </li>
        <% else %>
        	<li> <%= link_to "Welcome, Guest!", root_path %> </li>
        	<li> <%= link_to "Sign In", new_user_registration_path %></li>
        <% end %>
        
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if controller.controller_name == "storefront" %>
    <div class="jumbotron">
      <h1>Welcome to Amalizon!</h1>
      <h6>buy things, spend money</h6>
    </div>
  <% end %>




<div class="container">
	<%= yield %>
</div>

</body>
</html>